/* dOS — mock car database (Mexico market, 2026 prototype data)
 *
 * All figures are illustrative placeholders for prototype purposes only.
 * Monthly payment estimates assume a typical 48-month finance plan after the
 * user's down payment; they are recomputed at runtime in engine.js.
 */

window.DOS_CARS = [
  {
    id: "kia-rio",
    name: "Kia Rio",
    type: "Hatchback",
    priceMXN: 320000,
    seats: 5,
    trunkLiters: 325,
    badges: ["Low cost of ownership", "City-friendly"],
    scores: { safety: 6, fuel: 8, comfort: 5, design: 6, tech: 5, status: 4, resale: 6, maintenance: 9 },
    fuelKmPerL: 17.5,
    insuranceMXNYear: 14000,
    maintenanceMXNYear: 7000,
    resaleRetention3y: 0.62,
    blurb: "A no-drama, low-cost commuter. Cheap to run, easy to park, easy to resell.",
    fits: ["Budget-conscious commuter", "Comfort-first urban driver"]
  },
  {
    id: "nissan-versa",
    name: "Nissan Versa",
    type: "Sedan",
    priceMXN: 345000,
    seats: 5,
    trunkLiters: 482,
    badges: ["Big trunk", "Cheap parts"],
    scores: { safety: 6, fuel: 8, comfort: 6, design: 5, tech: 5, status: 4, resale: 7, maintenance: 9 },
    fuelKmPerL: 17,
    insuranceMXNYear: 13500,
    maintenanceMXNYear: 6500,
    resaleRetention3y: 0.66,
    blurb: "Mexico's value-sedan default. Roomy trunk, dirt-cheap service, strong resale.",
    fits: ["Budget-conscious commuter", "Practical long-term owner", "Young family optimizer"]
  },
  {
    id: "vw-jetta",
    name: "Volkswagen Jetta",
    type: "Sedan",
    priceMXN: 470000,
    seats: 5,
    trunkLiters: 510,
    badges: ["Solid highway feel", "Premium-ish cabin"],
    scores: { safety: 7, fuel: 7, comfort: 7, design: 7, tech: 6, status: 6, resale: 6, maintenance: 6 },
    fuelKmPerL: 15.5,
    insuranceMXNYear: 17000,
    maintenanceMXNYear: 11000,
    resaleRetention3y: 0.58,
    blurb: "Feels a class above on the highway. A confident all-rounder for mixed driving.",
    fits: ["Comfort-first urban driver", "Practical long-term owner", "Status-conscious buyer"]
  },
  {
    id: "mazda3",
    name: "Mazda 3",
    type: "Sedan",
    priceMXN: 490000,
    seats: 5,
    trunkLiters: 444,
    badges: ["Best-in-class design", "Fun to drive"],
    scores: { safety: 8, fuel: 7, comfort: 8, design: 9, tech: 7, status: 7, resale: 7, maintenance: 6 },
    fuelKmPerL: 15,
    insuranceMXNYear: 17500,
    maintenanceMXNYear: 10500,
    resaleRetention3y: 0.64,
    blurb: "Punches way above its price on design and cabin feel. The 'nice things' choice.",
    fits: ["Comfort-first urban driver", "Status-conscious buyer", "Tech-forward driver"]
  },
  {
    id: "hyundai-creta",
    name: "Hyundai Creta",
    type: "SUV",
    priceMXN: 480000,
    seats: 5,
    trunkLiters: 433,
    badges: ["Value SUV", "Good warranty"],
    scores: { safety: 7, fuel: 7, comfort: 7, design: 7, tech: 7, status: 6, resale: 7, maintenance: 7 },
    fuelKmPerL: 14.5,
    insuranceMXNYear: 16500,
    maintenanceMXNYear: 9000,
    resaleRetention3y: 0.65,
    blurb: "The sensible family SUV. Tall seating, real space, sane running costs.",
    fits: ["Young family optimizer", "Practical long-term owner", "Comfort-first urban driver"]
  },
  {
    id: "kia-seltos",
    name: "Kia Seltos",
    type: "SUV",
    priceMXN: 520000,
    seats: 5,
    trunkLiters: 433,
    badges: ["Loaded tech", "Strong warranty"],
    scores: { safety: 8, fuel: 6, comfort: 7, design: 8, tech: 8, status: 6, resale: 7, maintenance: 7 },
    fuelKmPerL: 13.5,
    insuranceMXNYear: 17000,
    maintenanceMXNYear: 9500,
    resaleRetention3y: 0.66,
    blurb: "Tech-heavy compact SUV with a long warranty. Good for gadget-minded families.",
    fits: ["Young family optimizer", "Tech-forward driver", "Status-conscious buyer"]
  },
  {
    id: "toyota-corolla-cross-hybrid",
    name: "Toyota Corolla Cross Hybrid",
    type: "Electric / Hybrid",
    priceMXN: 620000,
    seats: 5,
    trunkLiters: 487,
    badges: ["Hybrid efficiency", "Bulletproof reliability"],
    scores: { safety: 9, fuel: 10, comfort: 7, design: 7, tech: 7, status: 7, resale: 9, maintenance: 8 },
    fuelKmPerL: 22,
    insuranceMXNYear: 18500,
    maintenanceMXNYear: 7500,
    resaleRetention3y: 0.74,
    blurb: "Sips fuel, rarely breaks, holds its value. The long-term rational pick.",
    fits: ["Practical long-term owner", "Young family optimizer", "Road trip family buyer"]
  },
  {
    id: "toyota-rav4",
    name: "Toyota RAV4",
    type: "SUV",
    priceMXN: 760000,
    seats: 5,
    trunkLiters: 580,
    badges: ["Top resale", "Road-trip ready"],
    scores: { safety: 9, fuel: 7, comfort: 8, design: 7, tech: 7, status: 8, resale: 9, maintenance: 8 },
    fuelKmPerL: 14,
    insuranceMXNYear: 20000,
    maintenanceMXNYear: 9000,
    resaleRetention3y: 0.78,
    blurb: "The default 'safe big decision'. Space, safety, and resale you won't regret.",
    fits: ["Road trip family buyer", "Family with kids", "Practical long-term owner"]
  },
  {
    id: "honda-crv",
    name: "Honda CR-V",
    type: "SUV",
    priceMXN: 790000,
    seats: 5,
    trunkLiters: 589,
    badges: ["Spacious", "Comfortable"],
    scores: { safety: 9, fuel: 7, comfort: 9, design: 7, tech: 8, status: 8, resale: 8, maintenance: 7 },
    fuelKmPerL: 13.5,
    insuranceMXNYear: 20500,
    maintenanceMXNYear: 10000,
    resaleRetention3y: 0.72,
    blurb: "Roomy, calm, and family-proof. A comfort-first SUV for long ownership.",
    fits: ["Road trip family buyer", "Comfort-first urban driver", "Young family optimizer"]
  },
  {
    id: "toyota-hilux",
    name: "Toyota Hilux",
    type: "Pickup",
    priceMXN: 820000,
    seats: 5,
    trunkLiters: 0,
    badges: ["Workhorse", "Legendary resale"],
    scores: { safety: 7, fuel: 5, comfort: 6, design: 6, tech: 5, status: 7, resale: 9, maintenance: 8 },
    fuelKmPerL: 11,
    insuranceMXNYear: 21000,
    maintenanceMXNYear: 11000,
    resaleRetention3y: 0.80,
    blurb: "Built to work and survive. Unbeatable resale, but thirsty and basic inside.",
    fits: ["Work / business", "Practical long-term owner"]
  },
  {
    id: "mg-zs",
    name: "MG ZS",
    type: "SUV",
    priceMXN: 380000,
    seats: 5,
    trunkLiters: 448,
    badges: ["Most features per peso", "Aggressive pricing"],
    scores: { safety: 6, fuel: 7, comfort: 6, design: 7, tech: 8, status: 5, resale: 4, maintenance: 6 },
    fuelKmPerL: 14,
    insuranceMXNYear: 16000,
    maintenanceMXNYear: 9000,
    resaleRetention3y: 0.50,
    blurb: "Tons of kit for the money — but weaker resale and a less proven track record.",
    fits: ["Budget-conscious commuter", "Tech-forward driver", "Young family optimizer"]
  },
  {
    id: "byd-dolphin",
    name: "BYD Dolphin",
    type: "Electric / Hybrid",
    priceMXN: 560000,
    seats: 5,
    trunkLiters: 345,
    badges: ["Pure electric", "Very low running cost"],
    scores: { safety: 7, fuel: 10, comfort: 7, design: 8, tech: 9, status: 7, resale: 5, maintenance: 9 },
    fuelKmPerL: 99,
    insuranceMXNYear: 18000,
    maintenanceMXNYear: 4000,
    resaleRetention3y: 0.52,
    blurb: "Cheap to run and tech-forward EV — if you can charge it and accept resale risk.",
    fits: ["Tech-forward driver", "Comfort-first urban driver", "Budget-conscious commuter"]
  },
  {
    id: "mazda-cx5",
    name: "Mazda CX-5",
    type: "SUV",
    priceMXN: 680000,
    seats: 5,
    trunkLiters: 442,
    badges: ["Premium-feel cabin", "Great to drive"],
    scores: { safety: 8, fuel: 6, comfort: 9, design: 9, tech: 7, status: 8, resale: 7, maintenance: 6 },
    fuelKmPerL: 12.5,
    insuranceMXNYear: 19500,
    maintenanceMXNYear: 11500,
    resaleRetention3y: 0.66,
    blurb: "Feels near-luxury for the price. The aspirational SUV that's still attainable.",
    fits: ["Status-conscious buyer", "Comfort-first urban driver", "Young family optimizer"]
  },
  {
    id: "vw-tiguan",
    name: "Volkswagen Tiguan",
    type: "SUV",
    priceMXN: 720000,
    seats: 7,
    trunkLiters: 520,
    badges: ["Optional 7 seats", "Grown-up feel"],
    scores: { safety: 8, fuel: 6, comfort: 8, design: 7, tech: 7, status: 7, resale: 6, maintenance: 6 },
    fuelKmPerL: 12.5,
    insuranceMXNYear: 19000,
    maintenanceMXNYear: 12000,
    resaleRetention3y: 0.57,
    blurb: "Roomy, refined, optional third row — but watch the maintenance bills.",
    fits: ["Family with kids", "Road trip family buyer", "Status-conscious buyer"]
  }
];
